Fix Keil C51 compilation error: change bit array to unsigned char
Keil C51 does not support arrays of 'bit' type. Changed
ema_initialized from 'bit' array to 'unsigned char' array
to resolve compilation error C168.