Fix Keil C51 compilation error: change bit array to unsigned char array
Fixed error C168 caused by using bit array type which is not supported
in Keil C51 compiler. Changed is_settled from 'bit' array to 'unsigned char'
array for compatibility.

Error fixed:
- Line 449: error C168: 'is_settled': array of bit
- Line 466: error C187: not an lvalue

The functionality remains identical - just using unsigned char (0/1)
instead of bit type for array indexing compatibility.